# Generated by Django 6.1 on 2026-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "speaker",
                    models.CharField(
                        choices=[("user", "User"), ("llm", "LLM")], max_length=4
                    ),
                ),
                ("message", models.TextField()),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat",
            },
        ),
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "chatroom_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("chatroom_name", models.CharField(default="새 대화", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chatroom",
            },
        ),
        migrations.CreateModel(
            name="ChatSource",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_id", models.IntegerField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                ("page", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_source",
            },
        ),
    ]
