# Generated by Django 6.1 on 2026-08-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="chatroom",
            field=models.ForeignKey(
                db_column="chatroom_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatsource",
            name="chat",
            field=models.ForeignKey(
                db_column="chat_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
            ),
        ),
    ]
