"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SESSION_SECRET_KEY", "django-insecure-iuhcaw8dctfgs&=m$ed2c8#7+pb&*27q$te*q11n9wdm(mwe^w")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "chat",
    "documents.apps.DocumentsConfig",
    "legacy_import.apps.LegacyImportConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


def mysql_database_config(database_url: str, *, variable_name: str) -> dict:
    """Build Django MySQL settings from one explicit environment variable."""

    parsed_url = urlparse(database_url)
    database_name = parsed_url.path.lstrip("/")

    if not parsed_url.scheme.startswith("mysql"):
        raise ValueError(f"{variable_name} must use a MySQL URL.")
    if not parsed_url.hostname or not database_name:
        raise ValueError(
            f"{variable_name} must include a MySQL host and database name."
        )

    query_params = parse_qs(parsed_url.query)
    return {
        "ENGINE": "django.db.backends.mysql",
        "NAME": unquote(database_name),
        "USER": unquote(parsed_url.username or ""),
        "PASSWORD": unquote(parsed_url.password or ""),
        "HOST": parsed_url.hostname,
        "PORT": parsed_url.port or 3306,
        "OPTIONS": {
            "charset": query_params.get("charset", ["utf8mb4"])[0],
        },
    }


def is_same_mysql_database(first: dict, second: dict) -> bool:
    """Return whether two Django connection settings identify one MySQL DB."""

    return (
        first["NAME"] == second["NAME"]
        and str(first.get("HOST", "")).casefold()
        == str(second.get("HOST", "")).casefold()
        and str(first.get("PORT", 3306)) == str(second.get("PORT", 3306))
    )


DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": mysql_database_config(DATABASE_URL, variable_name="DATABASE_URL")
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Normal Django/RAG runtime uses only ``default``. This optional connection is
# exclusively for the one-off legacy importer; its models reject writes and
# its router blocks migrations on the source database.
LEGACY_DATABASE_URL = os.getenv("LEGACY_DATABASE_URL")
if LEGACY_DATABASE_URL:
    legacy_database = mysql_database_config(
        LEGACY_DATABASE_URL,
        variable_name="LEGACY_DATABASE_URL",
    )
    if DATABASE_URL and is_same_mysql_database(DATABASES["default"], legacy_database):
        raise ValueError(
            "LEGACY_DATABASE_URL must point to a different physical database "
            "than DATABASE_URL."
        )
    DATABASES["legacy"] = legacy_database

DATABASE_ROUTERS = ["legacy_import.db_router.LegacyImportRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Session configuration
SESSION_COOKIE_AGE = int(os.getenv("SESSION_MAX_AGE_SECONDS", str(3 * 60 * 60)))
SESSION_COOKIE_NAME = "session"


# Custom user model
AUTH_USER_MODEL = "users.User"


# External API URLs
CHAT_API_BASE_URL = os.getenv("CHAT_API_BASE_URL")
CHAT_API_TIMEOUT_SECONDS = int(os.getenv("CHAT_API_TIMEOUT_SECONDS", "70"))
DOC_API_BASE_URL = os.getenv("DOC_API_BASE_URL")
