name: Deploy Test

on:
  push:
    branches:
      - deployment-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            hostname
            docker --version

            cd ~/SKN32-4th-2Team
            git pull origin deployment-test
